Analytics V0.0.1. Tested with single_stream
darcyai/darcyai pull request #11
Opened 2022-07-26 04:13 UTC by Pixcell

2022-07-26 20:09 UTC, baghbidi requested changes

2022-07-26 20:09 UTC, baghbidi commented on src/darcyai/pipeline.py
> +                            pass
These try..except blocks are a little confusing... May be move all the reporter stuff to methods that ignore exceptions and call those methods here in the `pipeline.run`

2022-07-26 20:09 UTC, baghbidi commented on src/darcyai/reporter/analytics_reporter.py
> +    return
Not needed

2022-07-26 20:09 UTC, baghbidi commented on src/darcyai/reporter/analytics_reporter.py
> +    print(host)
Remove

2022-07-26 20:09 UTC, baghbidi commented on src/darcyai/reporter/analytics_reporter.py
> +      return
`pass`

2022-07-28 20:25 UTC, baghbidi approved these changes

2022-07-28 21:25 UTC, neilotoole requested changes
Initial pass, looks good to me.

Main change is to favor the name `telemetry` instead of `analytics` or `reporting`. It's a subtle change in emphasis, but that's the one we're going with. Sounds less creepy.

2022-07-28 21:25 UTC, neilotoole commented on src/darcyai/pipeline.py
> +    disable_reporting (bool): Disables anonymous usage collection. Defaults to `False`.
change to `disable_telemetry`

2022-07-28 21:25 UTC, neilotoole commented on src/darcyai/pipeline.py
> +                 disable_reporting: bool = False,):
change to `disable_telemetry`

2022-07-28 21:25 UTC, neilotoole commented on src/darcyai/pipeline.py
> +        if disable_reporting is not None:
change to `disable_telemetry`

2022-07-28 21:25 UTC, neilotoole commented on src/darcyai/pipeline.py
> +        self.__disable_reporting = disable_reporting
change to `disable_telemetry`

2022-07-28 21:25 UTC, neilotoole commented on src/darcyai/pipeline.py
> +        reporter = AnalyticsReporter(darcyai_version, self.__disable_reporting)
Change from `AnalyticsReporter` to `TelemetryReporter`.

2022-07-28 21:25 UTC, neilotoole commented on src/darcyai/reporter/analytics_reporter.py
> +import analytics
Change package/module/file from `src/darcyai/reporter/analytics_reporter.py` to `src/darcyai/telemetry/telemetry_reporter.py`. Basically, `telemetry` is now the preferred name for `analytics`.

2022-07-28 21:35 UTC, neilotoole commented on src/darcyai/pipeline.py
> +    ...                     disable_reporting=False)
change to `disable_telemetry`

2023-08-07 02:24 UTC, closed without merging